name: Update Applist
# Controls when the workflow will run
on:
  push:
    branches:
      - master
    paths:
    - '.github/workflows/update_applist.yml'
  # run at 2:00 UTC every day
  schedule:
     - cron: '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows you to send a dispatch event from another repository to run this actions
  repository_dispatch:
    types: [update applist]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-applist:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Generate pi-apps applist
        run: |
          sudo apt update
          sudo apt install gnuplot jq moreutils -y
          git clone --depth 1 https://github.com/Botspot/pi-apps.git /tmp/pi-apps
          cd $GITHUB_WORKSPACE
          cd src/wiki/getting-started
          sed -i 's;\\"https://github.com/Botspot/pi-apps/blob/master/apps/$script_url/icon-64.png?raw=true\\";\\"/img/app-icons/$script/icon-64.png\\";g' /tmp/pi-apps/.github/workflows/update-wiki.sh
          GITHUB_WORKSPACE=/tmp/pi-apps /tmp/pi-apps/.github/workflows/update-wiki.sh
          echo "---
          layout: layouts/wiki-toc.njk
          eleventyNavigation:
            key: Apps List
            parent: Getting Started
            order: 6
          ---" > apps-list.md
          cat Apps-List.md >> apps-list.md
          sed -i 's/^# /## /' apps-list.md

          rm Apps-List.md
          
          rm -rf $GITHUB_WORKSPACE/src/img/app-icons
          mkdir -p $GITHUB_WORKSPACE/src/img/app-icons/
          cd /tmp/pi-apps/apps
          cp --parent ./*/icon-64.png $GITHUB_WORKSPACE/src/img/app-icons/

      - name: Push changes to repo
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          default_author: github_actions
          message: |
            Update applist, run by GitHub Actions

