name: Update Applist
# Controls when the workflow will run
on:
  # run at 2:00 UTC every day
  schedule:
     - cron: '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows you to send a dispatch event from another repository to run this actions
  repository_dispatch:
    types: [update applist]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-applist:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Generate pi-apps applist
        run: |
          sudo apt update
          sudo apt install gnuplot jq moreutils -y
          git clone --depth 1 https://github.com/Botspot/pi-apps.git /tmp/pi-apps
          cd $GITHUB_WORKSPACE
          cd src/wiki/getting-started
          /tmp/pi-apps/.github/workflows/update-wiki.sh
          cat Apps-List.md

      - name: Push changes to repo
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          default_author: github_actions
          message: |
            Update applist, run by GitHub Actions

